server:
  port: 8080

spring:
  application:
    name: pack-service

  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
